services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: metabase_internal_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: metabaseappdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - postgres # <--- يعتمد الآن على postgres
    ports:
      - "3001:3000"
    environment:
      # --- إعدادات قاعدة بيانات Metabase الداخلية (تستخدم PostgreSQL) ---
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_HOST: postgres # <--- اسم خدمة PostgreSQL
      MB_DB_PASS: mysecretpassword
    restart: unless-stopped

volumes:
  mongo-data:
  postgres-data: # <--- إضافة volume لـ postgres
